feat(build): implement build command
npm/tink pull request #29
Opened 2018-11-13 06:04 UTC by BeniCheni

Refer to [tink-build topic](https://npm.community/t/tink-implement-tink-build/3313).

2018-11-13 06:07 UTC, BeniCheni commented on bin/tink.js
> +  ['shell', require('../lib/commands/shell.js')]
Minor FYI: ☝️while adding the required `build.js`, why not sort these items alphabetically.
(Happy to revert sort if it's bad idea.)

2018-11-13 06:10 UTC, BeniCheni commented on lib/commands/build.js
> +  })
Minor FYI: these default values of the `BuildConfig` are based on my best guesses, while reading code about how these option keys are being used in [npm-lifecycle/index.js](https://github.com/npm/npm-lifecycle/blob/latest/index.js).

Please advise if any of these default values, or the way of how this config object is written, can be improved. 🙏

2018-11-13 12:47 UTC, zkat requested changes
Just a few small nits so far. Looking forward to having tests for it! 💚 Everything looks great and I appreciate the contribution!

2018-11-13 12:47 UTC, zkat commented on lib/commands/build.js
> +  const findPrefix = require('find-npm-prefix')
This is available as `libnpm.getPrefix()`

2018-11-13 12:47 UTC, zkat commented on lib/commands/build.js
> +  const readJson = require('read-package-json')
This one is available as `libnpm.readJSON()`

2018-11-13 12:47 UTC, zkat commented on lib/commands/build.js
> +          console.error(`There was an error reading ${packageJson}`)
`libnpm.log.error()` for this and the one below, please.

2018-11-15 03:58 UTC, BeniCheni commented
Hi @zkat. Updated per the great nits you pointed out, wrote a basic test to assert `true` to validate the successful execution of the `build` command. Hopefully, this `build` PR is in good shape for review again for a wrap. Please review at convenience.

P.S.:
For the [access PR](https://github.com/npm/tink/pull/12), all the `access` subcommands are implemented & review comments have been addressed. I'd just like to write a test for some % coverage to work towards the PR "landing". Will ping you on that PR once I have test(s) in.

2018-11-20 05:04 UTC, BeniCheni commented
Ping/CC @zkat. Friendly FYI the branch of this PR has been rebased with `latest`, after the recent merge of other PRs. This PR should be in good shape for final review.

2018-11-20 12:22 UTC, zkat commented on lib/commands/build.js
> +      libnpm.readJSON(packageJSON)
You should use an `await` here as well and get rid of the .then()s

2018-11-20 15:58 UTC, BeniCheni commented
@zkat, indeed, I was able to improve the code to adapt `await` syntax to omit the `.then` usage in [this commit](https://github.com/npm/tink/pull/29#discussion_r234980519). Please take a quick look at convenience. Thanks!

2018-11-20 18:20 UTC, zkat approved these changes

2018-11-20 18:21 UTC, merged