refactor(access): Improve Access Implementation
npm/tink pull request #34
Opened 2018-11-21 03:30 UTC by BeniCheni

Since #12 is merged for `tink access`, this follow-up PR attempts to improve:
* use `await` to rewrite `.then` syntax
* remove unneeded `.catch` on await code
* address an `TODO` item:
  * call `whoami` when no "user" is provided to `ls-packages` option.

2018-11-21 14:45 UTC, zkat requested changes
Changes look mostly good -- can you manually test these commands to make sure they're working?

2018-11-21 14:45 UTC, zkat commented on lib/commands/access.jsx
> +    const prefix = await libnpm.findPrefix(process.cwd())
It's getPrefix

2018-11-21 14:45 UTC, zkat commented on lib/commands/access.jsx
> +      libnpm.readJson(
readJSON*

2018-11-26 01:43 UTC, BeniCheni commented
> ... can you manually test these commands to make sure they're working?

Corrected the bugs you caught in your review comments. Fixed in [commit 3a4f013]()

2018-11-26 01:46 UTC, BeniCheni commented
> ... can you manually test these commands to make sure they're working?

Corrected the bugs you caught in your review comments. Fixed in [commit 3a4f013](https://github.com/npm/tink/pull/34/commits/3a4f01356f572ff92be68e8b11f95e5c8ffbdbc5). Tested the commands manually to ensure working status, e.g. Thanks for your review! 🙏👍:
```
bchen in ~/github/tink on git:tink-access-refactor [20:41:51]
→ tink access ls-collaborators                           
┌────────┬────────────┐
│ collab │ role       │
├────────┼────────────┤
│ zkat   │ read-write │
└────────┴────────────┘
```

2018-11-26 05:55 UTC, zkat approved these changes
Everything looks good now!

2018-11-26 05:56 UTC, merged